chore: be consistent between files regarding spaces and alignements
cozy/cozy-onboarding-v3 pull request #17
Opened 2017-04-13 08:17 UTC by lespacedunmatin

Purely presentationnal PR.

2017-04-13 12:33 UTC, gregorylegarec requested changes
Thanks @lespacedunmatin, looks ok 👍 
Just a change request about indentation of "splitted lines".

2017-04-13 12:33 UTC, gregorylegarec commented on src/config/steps/fing.coffee
> +        instance.attributes \
The two following lines should also be indented, as they are the continuity of the first one, like this :
```js
    ...
    isActive: (instance) ->
        instance.attributes \
            && instance.attributes.context \
            && instance.attributes.context.tolowerCase() is 'fing'
```

2017-04-13 12:33 UTC, gregorylegarec commented on src/config/steps/maif.coffee
> +        instance.attributes \
Same remark below this line.

2017-04-21 12:41 UTC, gregorylegarec approved these changes

2017-04-21 12:42 UTC, merged

2017-04-21 12:42 UTC, gregorylegarec commented
Thanks @lespacedunmatin

2017-04-21 14:35 UTC, lespacedunmatin commented on src/config/steps/fing.coffee
> +        instance.attributes \
I do not understand that way of indenting code, to me it leads to poorly indented code like : 
```
if (
  toto
    && tata
) {
// do stuff
}
```

2017-04-24 21:04 UTC, gregorylegarec commented on src/config/steps/fing.coffee
> +        instance.attributes \
@lespacedunmatin Sorry I missed your comment. The thing is that the whole app is indented this way and we need to keep consistency.