feat: add a context maif_fing that allows to get both MAIF and FING
cozy/cozy-onboarding-v3 pull request #20
Opened 2017-04-18 14:27 UTC by lespacedunmatin

2017-04-18 17:29 UTC, GoOz approved these changes
Looks good to me 👍

2017-04-19 11:43 UTC, gregorylegarec commented on src/styles/app.styl
> +    margin-top 27px
@GoOz : is it ok to have a dimension in pixels here ? Where does `27` comes from ?

2017-04-19 12:03 UTC, GoOz commented on src/styles/app.styl
> +    margin-top 27px
oh right. Missed this one. The thing is there's no Cozy-UI on this repo, so we can't use functions like em()… Sooooo until then let's use em by doing do the math ourselves

2017-04-19 12:08 UTC, gregorylegarec commented
@lespacedunmatin On Chrome and Firefox, MAIF service thumbnail layout is broken.
![capture d ecran 2017-04-19 a 14 04 15](https://cloud.githubusercontent.com/assets/776764/25179239/4c993faa-2509-11e7-8162-849529b7083b.png)

2017-04-19 12:09 UTC, gregorylegarec commented
Also, I am not sure about Orange and EDF icon size, but I cannot check the mockup right now. I'll update my comment as soon as possible.

2017-04-19 12:39 UTC, lespacedunmatin commented on src/styles/app.styl
> +    margin-top 27px
Ok, I do the modification. 27 is the value that makes the design match de request from Zoe.

2017-04-19 12:45 UTC, gregorylegarec commented
@lespacedunmatin I confirm that the logos are to wide compared to the mockups. We should limit their height to render like MAIF one. EDF logo should be larger than Orange's one, so again I think it is just a matter of height.

2017-04-19 12:47 UTC, gregorylegarec requested changes
See my comments in main conversation.

2017-04-19 12:50 UTC, lespacedunmatin commented
I noticed that the logos where too big but I didn’t  want to make hazardous modifications on pieces I know litttle about. I will make the modifications.

2017-04-19 15:07 UTC, gregorylegarec commented
Thanks @lespacedunmatin, I think it's better but not yet coherent with the mockups and with the MAIF service aspect. I think we should use the same mechanism than the MAIF logo : https://github.com/cozy/cozy-onboarding-v3/blob/master/src/styles/app.styl#L517

I suggest:
```stylus
.service-logo--orange
    box-sizing border-box
    width 4.25rem
    height 4.25rem

.service-logo--edf
    box-sizing border-box
    height 4.25rem
```

2017-04-19 16:29 UTC, lespacedunmatin commented
Oh, I was wondering how to add that class. But it would be a tailored solution that would need a special work for every logo, that’s not very generic…

2017-04-19 16:34 UTC, gregorylegarec commented
@lespacedunmatin I agree, that's the main problem with logos, they all have specific dimensions. Do you think about an alternative ?

2017-04-21 16:39 UTC, lespacedunmatin commented
Ok, I heavily messed the log with my rebase…

2017-04-24 13:48 UTC, gregorylegarec commented
@lespacedunmatin Thanks that better now. Last think EDF icon is still too thin. Its `max-width` value should be `7rem`.

And we have a last request from @kelukelu, the `.service-name` element should have a `margin-bottom` equal to `1rem`. May you do this last change please ?

And don't worry about the history tree, I think that after the merge with master, it will be simpler to squash all the commits before merging.

2017-04-24 14:18 UTC, lespacedunmatin commented
Oh crap, the new rebase is even worse…

2017-04-24 14:54 UTC, lespacedunmatin commented
@gregorylegarec 8431e87 brings the modifications you submitted.

2017-04-24 19:38 UTC, gregorylegarec approved these changes

2017-04-24 19:39 UTC, gregorylegarec commented
Thanks @lespacedunmatin, I'll try to squash all the commit to get a more readable tree. 👍

2017-04-24 19:42 UTC, merged